# Generated by Django 3.2.7 on 2022-05-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='product_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='shipment.product'),
        ),
    ]
