# Generated by Django 4.0.4 on 2022-05-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="widgets",
            old_name="widgets",
            new_name="name",
        ),
    ]
