# Generated by Django 3.2.7 on 2022-05-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipments_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipments',
            new_name='Shipment',
        ),
    ]
