# Generated by Django 4.0.4 on 2022-05-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_widgets_user_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='widgets',
            field=models.CharField(choices=[('1', 'Info.'), ('2', 'Stat'), ('3', 'Charts'), ('4', 'Lists')], default='4', max_length=20),
        ),
    ]
