# Generated by Django 3.2.7 on 2022-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0002_rename_widgets_widgets_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userconfig",
            name="status",
        ),
        migrations.RemoveField(
            model_name="userconfig",
            name="widget",
        ),
        migrations.AddField(
            model_name="userconfig",
            name="widget",
            field=models.ManyToManyField(to="shipment.Widgets"),
        ),
    ]
