# Generated by Django 3.2.7 on 2022-05-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_rename_shipments_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
