# Generated by Django 3.2.7 on 2022-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0003_auto_20220518_2235"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
