# Generated by Django 4.0.4 on 2022-05-20 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0004_shipment_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconfig",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userwidget",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userconfig",
            name="widget",
            field=models.ManyToManyField(
                related_name="userconfig", to="shipment.widgets"
            ),
        ),
    ]
