# Generated by Django 4.0.4 on 2022-05-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_remove_user_widgets_user_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='widgets',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='shipment.widgets'),
        ),
    ]
