# Generated by Django 4.0.4 on 2022-05-17 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_alter_user_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='product_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shipment.product'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
