# Generated by Django 4.0.4 on 2022-05-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0010_remove_user_widgets_delete_widgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgets', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='widgets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.widgets'),
        ),
    ]
